#!/bin/bash
# QUICKSTART.sh - Get NFT Flappy running in minutes

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  NFT FLAPPY BIRD - QUICK START GUIDE${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

echo ""
echo -e "${YELLOW}📋 WHAT YOU'VE RECEIVED:${NC}"
echo "   1️⃣  Enhanced game frontend (with all features)"
echo "   2️⃣  Node.js backend (scores, leaderboard, Twitter OAuth)"
echo "   3️⃣  Solana smart contract (on-chain high scores)"
echo "   4️⃣  Integration code (connect everything together)"
echo "   5️⃣  Deployment guides (Vercel, Railway, Render)"

echo ""
echo -e "${YELLOW}⚡ FASTEST PATH TO LAUNCH (15 minutes):${NC}"
echo ""

echo -e "${GREEN}STEP 1: Frontend Deploy${NC}"
echo "  cd to your project folder"
echo "  npm install (if needed)"
echo "  Go to: https://vercel.com"
echo "  Click 'New Project' → Import your Git repo"
echo "  Deploy! (takes ~2 min)"
echo ""

echo -e "${GREEN}STEP 2: Backend Deploy${NC}"
echo "  Go to: https://railway.app"
echo "  Click 'New Project' → 'Deploy from GitHub'"
echo "  Connect your repo"
echo "  Add env vars from .env.example:"
echo "    • MONGODB_URI (get free one at mongodb.com)"
echo "    • TWITTER_CONSUMER_KEY/SECRET (from dev.twitter.com)"
echo "    • JWT_SECRET (generate random string)"
echo "  Deploy! (takes ~5 min)"
echo ""

echo -e "${GREEN}STEP 3: Connect Frontend to Backend${NC}"
echo "  In Vercel dashboard → Settings → Environment Variables"
echo "  Add: REACT_APP_API_URL=<your-railway-url>"
echo "  Redeploy"
echo ""

echo -e "${GREEN}STEP 4: Test${NC}"
echo "  ✅ Game loads"
echo "  ✅ Enter Twitter handle, load avatar"
echo "  ✅ Play game, submit score"
echo "  ✅ Check leaderboard (should update!)"
echo ""

echo ""
echo -e "${YELLOW}📚 DETAILED RESOURCES:${NC}"
echo ""
echo "  Game Code: ./nft-flappy-game.jsx"
echo "  Backend Code: ./flappy-backend/server.js"
echo "  Deployment Guide: ./DEPLOYMENT_GUIDE.md"
echo "  Integration Module: ./gameAPI.js"
echo "  Smart Contract: ./flappy-solana-contract/programs/flappy_nft/src/lib.rs"
echo ""

echo -e "${YELLOW}🔑 REQUIRED API KEYS (GET THESE FIRST):${NC}"
echo ""
echo "  1. Twitter API Keys"
echo "     Go: https://developer.twitter.com/en/portal/dashboard"
echo "     • Create App or use existing"
echo "     • Keys & Tokens → Get API Key & Secret"
echo "     • Settings → Callback URLs → Add your backend URL"
echo ""

echo "  2. MongoDB (Free)"
echo "     Go: https://www.mongodb.com/cloud/atlas"
echo "     • Sign up (free tier)"
echo "     • Create cluster"
echo "     • Copy connection string"
echo ""

echo "  3. Solana (Optional, for on-chain scores)"
echo "     Go: https://solana.com/developers"
echo "     • Install Solana CLI"
echo "     • Deploy contract to devnet first"
echo "     • Get Program ID"
echo ""

echo ""
echo -e "${YELLOW}💡 HOSTING COST BREAKDOWN:${NC}"
echo ""
echo "  ✅ Vercel Frontend: FREE (hobby tier)"
echo "  ✅ Railway Backend: ~\$5-10/month"
echo "  ✅ MongoDB: FREE (512MB)"
echo "  ✅ Solana Devnet: FREE"
echo "  ✅ Domain: ~\$12/year (optional)"
echo ""
echo "  💰 TOTAL: ~\$60-120/year"
echo ""

echo ""
echo -e "${YELLOW}🚀 DEPLOYMENT CHECKLIST:${NC}"
echo ""
echo "  [ ] Get Twitter API keys"
echo "  [ ] Create MongoDB Atlas account"
echo "  [ ] Push code to GitHub"
echo "  [ ] Deploy frontend to Vercel"
echo "  [ ] Deploy backend to Railway"
echo "  [ ] Add environment variables"
echo "  [ ] Test game end-to-end"
echo "  [ ] (Optional) Deploy Solana contract"
echo "  [ ] (Optional) Connect wallet integration"
echo "  [ ] Share with friends! 🎉"
echo ""

echo -e "${YELLOW}⚠️  COMMON GOTCHAS:${NC}"
echo ""
echo "  🔴 CORS Errors"
echo "     → Check FRONTEND_URL in backend .env matches your domain"
echo ""

echo "  🔴 Twitter OAuth Not Working"
echo "     → Verify callback URL in Twitter Developer Portal"
echo "     → Must be exactly: https://your-backend.com/api/auth/twitter/callback"
echo ""

echo "  🔴 Leaderboard Not Loading"
echo "     → Check MongoDB connection string"
echo "     → Verify IP whitelist on MongoDB Atlas"
echo ""

echo "  🔴 Scores Not Saving"
echo "     → Check backend logs (railway.app dashboard)"
echo "     → Verify MongoDB is running"
echo ""

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✨ You're ready to launch!${NC}"
echo ""
echo "Questions? Check DEPLOYMENT_GUIDE.md for detailed instructions"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
